### ISSUE TITLE
Improve feedback of compilation errors in breakpoint condition

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scala-debug-adapter#455]
```[tasklist]
### Tasks
- [x] Test in java-debug
- [x] Port fix from java-debug if available
- [ ] Or Implement fix ourselves
```
